#!/bin/bash

cd /home/pi/ogp
sudo chown -R pi:pi .
git stash save --keep-index
git pull
sudo rm /var/www/app.js
sudo cp www/app.js /var/www/app.js
sudo rm /var/www/style.css
sudo cp www/style.css /var/www/style.css
